### PR TITLE
Add Django 3.2 and Python 3.8 and 3.9 to dependencies

### LINKED ISSUE #30: Allow Django 3.2
Hi all,

The current pip release of django-add-default-value isn't allowing installation alongside Django 3.2

```
ERROR: Cannot install Django~=3.2 and django-add-default-value==0.7.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested Django~=3.2
    django-add-default-value 0.7.0 depends on Django<3.2 and >=1.11

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

### PR DESCRIPTION
**Pull request by David-Wobrock**
And stop blocking after Django 3.2

Fix #30

### CODE REVIEW

**Comment by David-Wobrock** [comment]
Ping @flixx :)

**Review by oscarhermoso — APPROVED** [review]
Thankyou @David-Wobrock :+1:

**Comment by David-Wobrock** [comment]
Isn't there any CI build on this repo anymore? I think there used to be a Travis configurated 🤔

**Comment by flixx** [comment]
Hi @oscarhermoso , thanks for creating the issue and @David-Wobrock thanks for the PR.
Merged it after testing it on my end as well.

@David-Wobrock I think travis was never running here. There is this: [https://github.com/3YOURMIND/django-add-default-value/issues/9](https://github.com/3YOURMIND/django-add-default-value/issues/9)

**Pull request merged**
