### PR TITLE
Python 3 update

### PR DESCRIPTION
**Pull request by igeligel**
## What kind of change does this PR introduce? ##

* [✖] Bugfix
* [✔] Feature
* [✖] Code style update
* [✖] Refactor
* [✖] Build-related changes
* [✖] Other, please describe

---

## Does this PR introduce a breaking change? ##

* [✖] No
* [✔] Yes: Python 2 support dropped

---

## Review and Merge ##

**Who**

* [✔] Last approver merges
* [✖] Pull request creator merges

**When**

* [✖] Merge after > 51% of the reviewers approved
* [✔] Merge after 100%  of the reviewers approved
* [✖] Merge after one reviewer approved

---

## Other information ##

- Used fstrings instead of normal formats
- deleted Python 2 notes and also fixed a typo

### CODE REVIEW

**Comment by flixx** [comment]
@igeligel I guess since fstrings are supported since Python 3.6, support for Python 3, 3.4 and 3.5 also needs to be dropped, right? Is that really necessary?

**Comment by igeligel** [comment]
The question is if it is really necessary to support Python 3, 3.4 and 3.5 since upgrades will not introduce any breaking changes.

**Comment by flixx** [comment]
OK. Could you update the setup.py then?

**Comment by mes3yd** [comment]
Declining this.
Readme updates were done in separate PR.
Django 1.11 still supports Python 2 till 2020. It's not in the way right now, and there's no up side just for format strings.
Feel free to rebase and reopen when you're adamant about it.

**Comment by igeligel** [comment]
Just an unpopular opinion:

Maybe break the things so enterprises are forced to upgrade their applications and if they cannot or do not want to do it, they need to invest in the engineering department of the company. If this is not supposed to happen it seem that other things are more important than engineering and the company has to live with the disadvantages of using an old version. If you still do not want to invest the money, the company might have other problems like a not well-running product, at least it is not generating enough profits.

**Pull request closed without merging**
